# Generated by Django 4.1.4 on 2023-01-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='application_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_business_startdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_registration_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legal_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notification_setting',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pan_or_gir',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='unread_notification_count',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that mobile already exists'}, max_length=50, null=True, unique=True),
        ),
    ]
