# Generated by Django 4.1.4 on 2023-01-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proprietorshop',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='vehicledeliveryperson',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='proprietorshop',
            name='shop_photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
