# Generated by Django 4.1.4 on 2023-02-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietorshop',
            name='shop_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SHOP STATE COUNTRY'),
        ),
        migrations.AddField(
            model_name='proprietorshop',
            name='shop_county',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SHOP COUNTY'),
        ),
        migrations.AddField(
            model_name='proprietorshop',
            name='shop_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SHOP STATE'),
        ),
        migrations.AlterField(
            model_name='proprietorshop',
            name='shop_address',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Shop Address'),
        ),
    ]
