# Generated by Django 4.1.4 on 2023-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_application_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='is_shop',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_submited',
        ),
        migrations.AddField(
            model_name='customuser',
            name='live_jobs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_jobs_posted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'company'), ('2', 'deliveryperson')], max_length=20),
        ),
    ]
