# Generated by Django 4.1.4 on 2023-01-28 20:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_proprietorshop_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietorshop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
