# Generated by Django 4.1.4 on 2023-01-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_is_verified_customuser_is_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, error_messages={'unique': 'A user with that email already exists'}, max_length=254, null=True),
        ),
    ]
