# Generated by Django 4.1.4 on 2023-02-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_proprietorshop_shop_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledeliveryperson',
            name='vehicle_type',
            field=models.CharField(choices=[('1', 'TWO-WHEELER'), ('2', 'THREE-WHEELER'), ('3', 'FOUR-WHEELER'), ('4', 'OTHER')], max_length=2),
        ),
    ]
