# Generated by Django 4.1.4 on 2023-01-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(error_messages={'unique': 'A user with that mobile already exists'}, max_length=50, unique=True),
        ),
    ]
