# Generated by Django 4.1.4 on 2023-01-29 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietorshop',
            name='is_job_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'PROPRIETOR'), ('2', 'DELIVERYPERSON')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proprietorshop',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proprietor'),
        ),
        migrations.CreateModel(
            name='VehicleDeliveryPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('1', 'PROPRIETOR'), ('2', 'DELIVERYPERSON')], max_length=2)),
                ('vehicle_number', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_name', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_job_live', models.BooleanField(default=False)),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': '2'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='DELIVERY-PERSON')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
