# Generated by Django 4.1.4 on 2023-01-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'proprieter'), ('2', 'deliveryperson')], max_length=20, null=True),
        ),
    ]
