# Generated by Django 4.1.4 on 2023-02-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_proprietorshop_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledeliveryperson',
            name='vehicle_number',
            field=models.CharField(blank=True, error_messages={'unique': 'dsds'}, max_length=10, null=True),
        ),
    ]
