# Generated by Django 4.1.4 on 2023-02-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_vehicledeliveryperson_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledeliveryperson',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
