# Generated by Django 4.1.4 on 2023-02-06 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_vehicledeliveryperson_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('PR', 'PROPRIETOR'), ('DP', 'DELIVERYPERSON')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proprietorshop',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'PR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proprietor'),
        ),
        migrations.AlterField(
            model_name='vehicledeliveryperson',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'DP'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='DELIVERY-PERSON'),
        ),
        migrations.AlterField(
            model_name='vehicledeliveryperson',
            name='vehicle_type',
            field=models.CharField(choices=[('TW', 'TWO-WHEELER'), ('THW', 'THREE-WHEELER'), ('FW', 'FOUR-WHEELER'), ('OT', 'OTHER')], max_length=3),
        ),
    ]
