# Generated by Django 4.1.4 on 2023-01-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists'}, max_length=254, null=True),
        ),
    ]
