# Generated by Django 4.1.4 on 2023-02-06 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_user_type_alter_proprietorshop_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietorshop',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_shop': True, 'user_type': 'PR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proprietor'),
        ),
    ]
