# Generated by Django 4.1.4 on 2023-02-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_proprietorshop_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='live_jobs_count',
            new_name='jobs_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_jobs_posted',
        ),
        migrations.AddField(
            model_name='proprietorshop',
            name='total_jobs_posted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
