# Generated by Django 4.1.4 on 2023-01-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customuser_adhar_photo_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adhar_photo_back',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adhar_photo_front',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
