# Generated by Django 4.1.4 on 2023-01-29 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_proprietorshop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietorshop',
            name='shop_gst',
            field=models.CharField(max_length=15, unique=True, verbose_name='GST NUMBER'),
        ),
        migrations.AlterField(
            model_name='proprietorshop',
            name='user',
            field=models.ForeignKey(error_messages={'user': 'sdss'}, limit_choices_to={'is_active': True, 'user_type': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proprietor'),
        ),
    ]
