# Generated by Django 4.1.4 on 2023-02-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_live_jobs_count_customuser_jobs_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adhar_photo_back',
            field=models.ImageField(max_length=500, upload_to='images/', verbose_name='Adharcard Back'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adhar_photo_front',
            field=models.ImageField(max_length=500, upload_to='images/', verbose_name='Adharcard front'),
        ),
    ]
