# Generated by Django 4.1.4 on 2023-02-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_adhar_photo_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietorshop',
            name='shop_photo',
            field=models.ImageField(blank=True, max_length=500, upload_to='images/'),
        ),
    ]
