# Generated by Django 4.1.4 on 2023-01-31 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_proprietorshop_shop_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietorshop',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proprietor'),
        ),
    ]
