# Generated by Django 4.1.4 on 2023-01-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_adhar_photo_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adhar_photo_back',
            field=models.ImageField(upload_to='images/', verbose_name='Adharcard Back'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adhar_photo_front',
            field=models.ImageField(upload_to='images/', verbose_name='Adharcard front'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_adhar_verified',
            field=models.BooleanField(default=False, verbose_name='AdharCard Verified'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_shop',
            field=models.BooleanField(default=False, verbose_name='have shop'),
        ),
    ]
