# Generated by Django 4.1.4 on 2023-01-19 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_customuser_adhar_photo_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProprietorShop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(max_length=150, verbose_name='Shop Name')),
                ('shop_shortdescribtion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Describtion')),
                ('shop_describtion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Describtion')),
                ('shop_address', models.TextField(max_length=500, verbose_name='Shop Address')),
                ('shop_gst', models.CharField(max_length=15, verbose_name='GST NUMBER')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proprietor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
